spring.datasource.url=jdbc:postgresql://localhost:5432/neonark
spring.datasource.username=postgres
spring.datasource.password=qwe123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always